#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
# Porting on Ophub by Manssizz (C) 2023

START=99

. /lib/functions/system.sh

boot() {
	case $(board_name) in
	rongpin,king3399)
		echo 56 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio56/direction
		echo 1 > /sys/class/gpio/gpio56/value
		echo 50 > /sys/class/gpio/export && echo high > /sys/class/gpio/gpio50/direction
        echo 56 > /sys/class/gpio/export && echo high > /sys/class/gpio/gpio56/direction
		;;
	esac
}